@driver-offer-bpp-host = http://localhost:8016
@adminToken = favorit-admin-0000000000000000-token

###
# @name profile
GET {{driver-offer-bpp-host}}/ui/orgAdmin/profile
token: {{adminToken}}

###
# @name listFarePolicies
GET {{driver-offer-bpp-host}}/ui/org/farePolicy
token: {{adminToken}}

###
@farePolicyToUpdate = {{listFarePolicies.response.body.oneWayFarePolicies[0].id}}


# @name updateSuv
POST {{driver-offer-bpp-host}}/ui/org/farePolicy/{{farePolicyToUpdate}}
Content-Type: application/json
token: {{adminToken}}

{
    "baseDistanceFare": 11,
    "perExtraKmFare":12,
    "baseDistance": 450,
    "extraKmFare": 13,
    "deadKmFare": 125,
    "driverMinExtraFee": 10,
    "driverMaxExtraFee": 30
}

###
# @name updateSuv2
POST {{driver-offer-bpp-host}}/ui/org/farePolicy/{{farePolicyToUpdate}}
Content-Type: application/json
token: {{adminToken}}

{
    "perExtraKmFare": 13,
    "baseDistance": 400,
    "extraKmFare": 30,
    "deadKmFare": 130,
    "driverMinExtraFee": 10,
    "driverMaxExtraFee": 30,
    "baseDistanceFare": 11
}